// <auto-generated />
using System;
using HctNetCoreLab12_EF.HctEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HctNetCoreLab12_EF.Migrations
{
    [DbContext(typeof(HctAppDBContext))]
    [Migration("20260930021651_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HctNetCoreLab12_EF.Models.HctCategory", b =>
                {
                    b.Property<int>("HctID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HctID"));

                    b.Property<DateTime>("HctCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HctName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("HctStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("HctID");

                    b.ToTable("HctCategory");
                });

            modelBuilder.Entity("HctNetCoreLab12_EF.Models.HctProduct", b =>
                {
                    b.Property<int>("HctID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HctID"));

                    b.Property<int>("HctCategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("HctCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HctDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("ntext");

                    b.Property<string>("HctImage")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HctName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("HctPrice")
                        .HasColumnType("real");

                    b.Property<float>("HctSalePrice")
                        .HasColumnType("real");

                    b.Property<byte>("HctStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("HctID");

                    b.HasIndex("HctCategoryID");

                    b.ToTable("HctProduct");
                });

            modelBuilder.Entity("HctNetCoreLab12_EF.Models.HctProduct", b =>
                {
                    b.HasOne("HctNetCoreLab12_EF.Models.HctCategory", "HctCategory")
                        .WithMany("HctProducts")
                        .HasForeignKey("HctCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HctCategory");
                });

            modelBuilder.Entity("HctNetCoreLab12_EF.Models.HctCategory", b =>
                {
                    b.Navigation("HctProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
